[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "phelipi", email = "ggizmeuamigo@gmail.com"},
]
dependencies = [
    "django>=4.1.7",
]
requires-python = ">=3.10"
license = {text = "n"}
